### ISSUE TITLE
PushShift Service is Down and Unable to Download Dataset

### ISSUE THREAD

**Issue by kimbochen** [honglizhan/CovidET#1]
Hello, thank you for publishing this interesting paper.  
I was trying to reproduce your results and downloading the data set, but PushShift seems to be out of service.  
After further research, it seems like both PSAW and PMAW are unable to retrieve all submissions prior to November 2022 ([source](https://www.reddit.com/r/pushshift/comments/10utf1d/first_day_trying_to_scrape_reddit_bad_timing/)).  
Is it possible for you to share the dataset through other means?  
Thank you for your help.

**Comment by honglizhan** [comment]
Hi, thanks for catching this! Yes I can share the dataset with you. My email address is honglizhan@utexas.edu. Could you shoot me an email please so that I can share through Google drive? 😜
